### PR TITLE
Power sensor

### PR DESCRIPTION
**Pull request by sakalauskas**
Getting lots of electric power cuts this winter so decided that I should automate a few things since I could get this info from the alarm system.

Instead of AT/AR statuses being saved as the last message, it will save the state as a binary sensor. Heartbeat isn’t incredibly useful sensor.

### CODE REVIEW

**Comment by eavanvalkenburg** [comment]
This looks good, thanks for the addition! 

One question, I haven't really looked at those messages, so are they also sent without a zone, similar to the RP messages?

**Comment by sakalauskas** [comment]
@eavanvalkenburg Yes, they are sent as zone = 0

After tinkering for a bit I found that after the home assistant restart, the state isn't restored/retrieved. I do not have the smoke/water sensors yet but I assume that is the same?

I think that's kind of "okay" since with these sensors we'd mostly be interested when fire starts/water leaks/power goes out.

**Comment by eavanvalkenburg** [comment]
Yeah, since those sensors are indeed driven just by a event coming in, they remain unknown until the first time they are called, after that it should pull the previous state out of storage after a reboot. Could you redo this PR against the `beta` branch?

**Comment by sakalauskas** [comment]
@eavanvalkenburg thanks, done!

**Comment by eavanvalkenburg** [comment]
Just released it in the pre-release channel under v0.3.11beta-3!

**Pull request merged**
